#!/bin/bash

function help_me()
{
	echo "Usage: $0 <5|7> [-v|-q]"
}

function set_version()
{
	IGNORE="^\s*(To activate the new configuration, you need to run:|service apache2 restart|Module php[0-9\.]* already disabled|Considering conflict php5 for php7.0:)\s*$"
	if [[ "$2" == "-q" ]]
	then
		IGNORE=""
	fi
	if [[ "$2" == "-v" ]]
	then
		IGNORE="$^"
	fi
	sudo a2dismod php5 | grep -vP "$IGNORE"
	sudo a2dismod php7.0 | grep -vP "$IGNORE"
	sudo a2enmod "php$1" | grep -vP "$IGNORE"
	sudo update-alternatives --set php "/usr/bin/php$1" | grep -vP "$IGNORE"
	sudo systemctl restart apache2.service
}

case "$1" in
	("5") set_version "5" "$2" ;;
	("7") set_version "7.0" "$2" ;;
	(*) help_me ;;
esac

exit 0
